workflows:
  default-workflow:
    name: Build APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --target=lib/main.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
